backend/config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :users
  get 'login', to: 'session#index', as: :login
  get 'auth/authsch/callback', to: 'session#callback'
  get 'logout', to: 'session#destroy', as: :logout
  get 'forbidden', to: 'session#forbidden', as: :forbidden
  post 'api/registrations', to: 'registrations#create'
  get 'api/available', to: 'api#available', as: :available
  get 'open_registrations', to: 'api#open', as: :open_registrations
  get 'close_registrations', to: 'api#close', as: :close_registrations
  root 'registrations#index'
end

backend/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SSSL Képzés Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if logged_in_as_accepted? %>
          <li class="nav-item">
            <%= link_to 'Regisztrációk', registrations_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% if logged_in_as_admin? %>
          <li class="nav-item">
            <%= link_to 'Felhasználók', users_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Kijelentkezés', logout_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Senior képzés Admin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container mt-5">
  <% if notice.present? %>
    <div class="alert alert-warning" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <%= yield %>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>